spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://160.16.115.5:3306/practice
    username: practice
    password: 2020Mysql@10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
